name: Commit on commit

on:
  push:
  workflow_dispatch:
  
jobs:
  commit:
    name: Commit README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date +%s > README.md
      - run: |
            chmod +x ./scripts/commit.sh
            ./scripts/commit.sh
